export const appStyles = {
  header: {
    padding: "10px 20px",
    backgroundColor: "#28A745",
    color: "#FFF",
    textAlign: "center",
    fontSize: "24px",
    fontWeight: "bold",
  },
  container: {
    display: "flex",
    flexDirection: "column",
    fontFamily: "'Roboto', sans-serif",
    backgroundColor: "#f8f9fa",
    color: "#333",
    margin: 0,
    padding: 0,
    width: "100vw",
    height: "100vh",
  },
  controlSection: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 10%",
    gap: "20px",
    backgroundColor: "#FFF",
    boxShadow: "0 2px 5px rgba(0, 0, 0, 0.1)",
    borderRadius: "8px",
    marginBottom: "20px",
  },
  datePickerContainer: {
    display: "flex",
    gap: "20px",
    padding: "10px",
  },
  datePickerLabel: {
    fontWeight: "bold",
    marginBottom: "10px",
    display: "block",
  },
  datePickerInput: {
    width: "150px",
    padding: "8px",
    border: "1px solid #CCC",
    borderRadius: "5px",
    fontSize: "16px",
  },
  plotSection: {
    position: "relative",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    margin: "20px",
    height: "calc(100vh - 160px)",
    minHeight: "400px",
  },

  spinnerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    zIndex: 10,
  },
  spinner: {
    width: "50px",
    height: "50px",
    border: "5px solid #ccc",
    borderTop: "5px solid #28A745",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
};
